// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int numberOfTests = Integer.parseInt(args[0]);

		int belowHalf = 0;
		int aboveHalf = 0;
		
		// sum the numberof times abve and below half
		for (int i = 0; i < numberOfTests; i++){
			double randomNumber = Math.random();
			if (randomNumber < 0.5) belowHalf += 1 ;
			else aboveHalf += 1;
		}

		double ratio = (double) belowHalf / aboveHalf;

		System.out.println("> 0.5:  " + belowHalf + " times");
		System.out.println("<= 0.5: " + aboveHalf + " times");

		if (aboveHalf > 0 && belowHalf > 0) System.out.println("Ratio:  " + ratio); 
		

	}
}
